brew "azure-cli"
brew "ca-certificates"
brew "cheat"
brew "coreutils"
brew "exiftool"
brew "ffmpeg"
brew "gh"
brew "git"
brew "jq"
brew "mactop"
brew "mas"
brew "media-info"
brew "mozjpeg"
brew "pipx"
brew "powershell"
brew "python"
brew "rclone"
brew "rsync"
brew "tlrc"
brew "tmux"
brew "wget"
brew "zsh-autocomplete"

cask "antigravity"
cask "antigravity-ide"
cask "chatgpt"
cask "google-chrome"
cask "google-drive"
cask "google-gemini"
cask "lm-studio"
cask "raspberry-pi-imager"
cask "visual-studio-code"
cask "vlc"

mas "Lightroom", id: 1451544217
mas "WhatsApp", id: 310633997
mas "Windows", id: 1295203466
