
# Rename all photos in the current directory based on their creation date
rename-photos() {
  exiftool "-filename<CreateDate" -d "%Y%m%d_%H%M%S%%-c.%%e" -r .
}

# Rename all videos in the current directory based on their creation date
rename-videos(){
  exiftool -api QuickTimeUTC "-filename<TrackCreateDate" -d "%Y%m%d_%H%M%S%%-c.%%e" -r .
}

# Add the specified number of hours to all the media files in the current directory
function add-hours() {
  if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: add-hours <hours> <file(s)>"
    return 1
  fi

  exiftool -overwrite_original -AllDates+="$1" "$2"
}

# Subtract the specified number of hours from all the media files in the current directory
function subtract-hours() {
  if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: subtract-hours <hours> <file(s)>"
    return 1
  fi

  exiftool -overwrite_original -AllDates-="$1" "$2"
}

# Compress a single video
compress-video() {
  local input="$1"
  local output_dir="$(dirname -- "$input")/crf23"
  local output="$output_dir/$(basename -- "$input")"
  mkdir -p "$output_dir"
  ffmpeg -i "$input" -map_metadata 0 -c:v libx265 -preset slow -crf 23 -c:a copy -tag:v hvc1 "$output" && \
    exiftool -overwrite_original -P -api QuickTimeUTC -tagsFromFile "$input" \
      -All:All \
      "-QuickTime:GPSCoordinates<QuickTime:GPSCoordinates" \
      "-Keys:GPSCoordinates<Keys:GPSCoordinates" \
      "-UserData:GPSCoordinates<UserData:GPSCoordinates" \
      "-ItemList:GPSCoordinates<ItemList:GPSCoordinates" \
      "-Make<Make" \
      "-Model<Model" \
      "-AndroidMake<AndroidMake" \
      "-AndroidModel<AndroidModel" \
      "$output"
}

# Compress all videos in the current directory
compress-videos() {
  for file in *.(mp4|MP4|mov|MOV|mkv|MKV)(N); do
    if [ -f "$file" ]; then
      compress-video "$file"
    fi
  done
}

# Compress a single photo
compress-photo() {
  local file=$1
  local quality=${2:-75}
  mkdir -p "$(dirname -- "$file")/$quality"
  cjpeg -quality "$quality" -outfile "$(dirname -- "$file")/$quality/$(basename -- "$file")" "$file"
}

# Compress all photos in the current directory
compress-photos() {
  local quality=${1:-75}
  autoload -Uz zargs
  local files=(*.(jpg|JPG|jpeg|JPEG)(N))
  if (( ${#files} > 0 )); then
    zargs -P 12 -I {} -- "${files[@]}" -- compress-photo '{}' "$quality"
  else
    echo "No JPG/JPEG photos found in the current directory."
  fi
}
