# Aliases
alias ..='cd ..'
alias dl='cd ~/Downloads'
alias gd='cd ~/Library/CloudStorage/GoogleDrive-YOUR_EMAIL@gmail.com/My\ Drive'
alias icloud='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs'
alias la='gls -ahl --group --color=auto'
alias ll='gls -hl --group --color=auto'
alias pip='pip3'
alias python='python3'
alias setup='~/projects/macbook-setup/setup.sh'
alias vnet='sudo route -n add -net 10.0.0.0/24 192.168.0.210'

# Exports
export CLICOLOR=1
export LSCOLORS=ExGxFxdxCxDxDxxbaDecac
export PROMPT="%F{green}%n@macbook%f:%F{blue}%5~%f%# " # Ubuntu style

# Options
setopt AUTO_CD
setopt CORRECT
setopt CORRECT_ALL
